// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VitroFit.API.Features.AdaptiveFitness;

#nullable disable

namespace VitroFit.API.Features.AdaptiveFitness.Data.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    [Migration("20260927111308_AddGymExercises")]
    partial class AddGymExercises
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fitness")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessApproval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Version")
                        .IsUnique();

                    b.ToTable("Approvals", "fitness");
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ScheduleJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SourceWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceWorkflowId")
                        .IsUnique();

                    b.HasIndex("UserId", "StartDate");

                    b.ToTable("Cycles", "fitness");
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "CreatedAt");

                    b.ToTable("Events", "fitness");
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BeginnerAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exercises", "fitness");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Sit back to a stable chair and stand with control.",
                            MuscleGroup = "legs",
                            Name = "Chair squat"
                        },
                        new
                        {
                            Id = 2,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Keep a straight body and press gently away from the wall.",
                            MuscleGroup = "chest",
                            Name = "Wall push-up"
                        },
                        new
                        {
                            Id = 3,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Hold a stable support and raise your heels slowly.",
                            MuscleGroup = "legs",
                            Name = "Standing calf raise"
                        },
                        new
                        {
                            Id = 4,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Sit upright and straighten each knee with control.",
                            MuscleGroup = "legs",
                            Name = "Seated knee extension"
                        },
                        new
                        {
                            Id = 5,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "March gently in place; count one repetition per knee lift.",
                            MuscleGroup = "full body",
                            Name = "Standing march"
                        },
                        new
                        {
                            Id = 6,
                            BeginnerAllowed = true,
                            Equipment = "dumbbells",
                            Instructions = "Use a comfortable light weight and keep elbows close to your sides.",
                            MuscleGroup = "arms",
                            Name = "Light dumbbell curl"
                        },
                        new
                        {
                            Id = 7,
                            BeginnerAllowed = true,
                            Equipment = "resistance_band",
                            Instructions = "Use a secure band anchor and draw elbows back with control.",
                            MuscleGroup = "back",
                            Name = "Seated band row"
                        },
                        new
                        {
                            Id = 8,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Keep elbows close to your sides and press gently away from the wall.",
                            MuscleGroup = "triceps",
                            Name = "Close-grip wall push-up"
                        },
                        new
                        {
                            Id = 9,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Stand facing a wall, place hands at chest height, and press with control.",
                            MuscleGroup = "chest",
                            Name = "Wall chest press"
                        },
                        new
                        {
                            Id = 10,
                            BeginnerAllowed = true,
                            Equipment = "resistance_band",
                            Instructions = "Use a secure band anchor and extend elbows without locking them.",
                            MuscleGroup = "triceps",
                            Name = "Band triceps press-down"
                        },
                        new
                        {
                            Id = 11,
                            BeginnerAllowed = true,
                            Equipment = "dumbbells",
                            Instructions = "Hinge slightly at the hips and raise light weights with control.",
                            MuscleGroup = "back",
                            Name = "Seated reverse fly"
                        },
                        new
                        {
                            Id = 12,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "From hands and knees, extend opposite arm and leg while keeping the trunk steady.",
                            MuscleGroup = "back",
                            Name = "Bird dog"
                        },
                        new
                        {
                            Id = 13,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Push hips back with a neutral spine, then stand tall.",
                            MuscleGroup = "legs",
                            Name = "Standing hip hinge"
                        },
                        new
                        {
                            Id = 14,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Lie on your back, press through your feet, and lift hips comfortably.",
                            MuscleGroup = "legs",
                            Name = "Glute bridge"
                        },
                        new
                        {
                            Id = 15,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Hold a stable support and lower only through a comfortable range.",
                            MuscleGroup = "legs",
                            Name = "Supported split squat"
                        },
                        new
                        {
                            Id = 16,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Stand against a wall and slide arms through a comfortable range while keeping posture tall.",
                            MuscleGroup = "back",
                            Name = "Wall angel"
                        },
                        new
                        {
                            Id = 17,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Make small controlled arm circles without weights and stop if uncomfortable.",
                            MuscleGroup = "arms",
                            Name = "Arm circles"
                        },
                        new
                        {
                            Id = 18,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Set bench to 30–45 degrees, press dumbbells from chest level to lockout with control.",
                            MuscleGroup = "chest",
                            Name = "Dumbbell incline press"
                        },
                        new
                        {
                            Id = 19,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Stand between cables set high, bring handles together in an arc in front of your chest.",
                            MuscleGroup = "chest",
                            Name = "Cable crossover"
                        },
                        new
                        {
                            Id = 20,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Sit on machine, grip handles at chest width, and press to full extension then lower with control.",
                            MuscleGroup = "chest",
                            Name = "Plate-loaded machine bench press"
                        },
                        new
                        {
                            Id = 21,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Lie on decline bench, unrack barbell, lower to lower chest, press up to lockout.",
                            MuscleGroup = "chest",
                            Name = "Decline barbell press"
                        },
                        new
                        {
                            Id = 22,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Lie on flat bench, hold barbell above chest, bend elbows to lower bar to forehead, extend back up.",
                            MuscleGroup = "triceps",
                            Name = "Lying barbell triceps extension"
                        },
                        new
                        {
                            Id = 23,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Hold one dumbbell with both hands overhead, lower behind head by bending elbows, press back up.",
                            MuscleGroup = "triceps",
                            Name = "Single dumbbell tricep overhead extension"
                        },
                        new
                        {
                            Id = 24,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Attach straight bar to high cable, grip underhand, keep elbows at sides and push bar down to full extension.",
                            MuscleGroup = "triceps",
                            Name = "Reverse grip cable tricep pushdown"
                        },
                        new
                        {
                            Id = 25,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Rest forearms on bench, hold barbell with palms up, curl wrists up and lower with control.",
                            MuscleGroup = "arms",
                            Name = "Wrist curls"
                        },
                        new
                        {
                            Id = 26,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Sit on incline bench set to ~75 degrees, press dumbbells from shoulder height to overhead.",
                            MuscleGroup = "upper body",
                            Name = "Incline shoulder press"
                        },
                        new
                        {
                            Id = 27,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Hold dumbbells at thighs, raise both arms to shoulder height in front, lower with control.",
                            MuscleGroup = "upper body",
                            Name = "Front raises"
                        },
                        new
                        {
                            Id = 28,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Hold cables at sides, raise arms out to shoulder height and lower slowly.",
                            MuscleGroup = "upper body",
                            Name = "Hanging side lateral raises"
                        },
                        new
                        {
                            Id = 29,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Stand with bar behind at hip height, shrug shoulders up and back, hold briefly.",
                            MuscleGroup = "back",
                            Name = "Smith machine back body shrugs"
                        },
                        new
                        {
                            Id = 30,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Attach rope to high cable, pull to face level splitting rope apart, squeeze rear delts.",
                            MuscleGroup = "back",
                            Name = "Face pulls"
                        },
                        new
                        {
                            Id = 31,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Grip barbell underhand shoulder-width, hinge at hips, row bar to lower chest, lower with control.",
                            MuscleGroup = "back",
                            Name = "Reverse grip barbell rows"
                        },
                        new
                        {
                            Id = 32,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Hinge at hips, hold dumbbells below chest, row both to sides of torso, lower with control.",
                            MuscleGroup = "back",
                            Name = "Bent-over dumbbell rows"
                        },
                        new
                        {
                            Id = 33,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Stand at high cable, arms extended, pull bar down to thighs keeping arms straight.",
                            MuscleGroup = "back",
                            Name = "Straight arm pulldowns"
                        },
                        new
                        {
                            Id = 34,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Lock feet in hyperextension bench, lower torso toward floor, raise back to parallel using lower back.",
                            MuscleGroup = "back",
                            Name = "Back extensions"
                        },
                        new
                        {
                            Id = 35,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Kneel at high cable with rope, crunch torso toward knees contracting abs, return under control.",
                            MuscleGroup = "core",
                            Name = "Cable crunches"
                        },
                        new
                        {
                            Id = 36,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Lie on back knees bent, rise to sitting position engaging abs, lower with control.",
                            MuscleGroup = "core",
                            Name = "Sit-ups"
                        },
                        new
                        {
                            Id = 37,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Lie flat or hang from bar, raise straight legs to 90 degrees and lower with control.",
                            MuscleGroup = "core",
                            Name = "Leg raises"
                        },
                        new
                        {
                            Id = 38,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Position bar on front delts in Smith machine, squat until thighs parallel, drive through heels to stand.",
                            MuscleGroup = "legs",
                            Name = "Smith machine front squats"
                        },
                        new
                        {
                            Id = 39,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Sit on leg extension machine, extend one leg to lockout, lower with control, alternate legs.",
                            MuscleGroup = "legs",
                            Name = "Single leg extensions"
                        },
                        new
                        {
                            Id = 40,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Hold barbell at hips, hinge back pushing hips back keeping bar close, feel hamstring stretch, drive hips forward to stand.",
                            MuscleGroup = "legs",
                            Name = "Romanian deadlifts"
                        },
                        new
                        {
                            Id = 41,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Stand on calf raise machine or step, rise onto toes fully, lower heel below platform.",
                            MuscleGroup = "legs",
                            Name = "Calf raises"
                        },
                        new
                        {
                            Id = 42,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Hold barbell with hands 6 inches apart, curl to shoulder height keeping elbows at sides, lower with control.",
                            MuscleGroup = "arms",
                            Name = "Close grip bicep curls"
                        },
                        new
                        {
                            Id = 43,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Hold barbell with hands wider than shoulders, curl to shoulder height, lower with control.",
                            MuscleGroup = "arms",
                            Name = "Wide grip bicep curls"
                        },
                        new
                        {
                            Id = 44,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Rest upper arm on preacher pad, curl dumbbell to shoulder, lower fully to stretch.",
                            MuscleGroup = "arms",
                            Name = "Single arm dumbbell preacher curls"
                        },
                        new
                        {
                            Id = 45,
                            BeginnerAllowed = true,
                            Equipment = "gym",
                            Instructions = "Hold barbell with overhand grip, curl to shoulder height keeping wrists neutral, lower with control.",
                            MuscleGroup = "arms",
                            Name = "Reverse curls"
                        });
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Days")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<string[]>("Equipment")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<bool>("ReviewRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("SessionMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("UserId");

                    b.ToTable("Profiles", "fitness");
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.PrimitiveCollection<string[]>("AffectedAreas")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<bool>("Pain")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("PerformedOn")
                        .HasColumnType("date");

                    b.Property<int>("Rpe")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Day")
                        .IsUnique();

                    b.ToTable("Progress", "fitness", t =>
                        {
                            t.HasCheckConstraint("CK_Progress_Day", "\"Day\" BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CK_Progress_Rpe", "\"Rpe\" BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PreviousWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PreviousWorkflowId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Workflows", "fitness");
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessApproval", b =>
                {
                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessCycle", b =>
                {
                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", null)
                        .WithMany()
                        .HasForeignKey("SourceWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessEvent", b =>
                {
                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessProgress", b =>
                {
                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", b =>
                {
                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", null)
                        .WithMany()
                        .HasForeignKey("PreviousWorkflowId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
