// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VitroFit.API.Features.AdaptiveFitness;

#nullable disable

namespace VitroFit.API.Features.AdaptiveFitness.Data.Migrations
{
    [DbContext(typeof(FitnessDbContext))]
    partial class FitnessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fitness")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessApproval", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Version")
                        .IsUnique();

                    b.ToTable("Approvals", "fitness");
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Step")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "CreatedAt");

                    b.ToTable("Events", "fitness");
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BeginnerAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Equipment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MuscleGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Exercises", "fitness");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Sit back to a stable chair and stand with control.",
                            MuscleGroup = "legs",
                            Name = "Chair squat"
                        },
                        new
                        {
                            Id = 2,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Keep a straight body and press gently away from the wall.",
                            MuscleGroup = "upper body",
                            Name = "Wall push-up"
                        },
                        new
                        {
                            Id = 3,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Hold a stable support and raise your heels slowly.",
                            MuscleGroup = "legs",
                            Name = "Standing calf raise"
                        },
                        new
                        {
                            Id = 4,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Sit upright and straighten each knee with control.",
                            MuscleGroup = "legs",
                            Name = "Seated knee extension"
                        },
                        new
                        {
                            Id = 5,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "March gently in place; count one repetition per knee lift.",
                            MuscleGroup = "full body",
                            Name = "Standing march"
                        },
                        new
                        {
                            Id = 6,
                            BeginnerAllowed = true,
                            Equipment = "dumbbells",
                            Instructions = "Use a comfortable light weight and keep elbows close to your sides.",
                            MuscleGroup = "arms",
                            Name = "Light dumbbell curl"
                        },
                        new
                        {
                            Id = 7,
                            BeginnerAllowed = true,
                            Equipment = "resistance_band",
                            Instructions = "Use a secure band anchor and draw elbows back with control.",
                            MuscleGroup = "back",
                            Name = "Seated band row"
                        },
                        new
                        {
                            Id = 8,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Keep elbows close to your sides and press gently away from the wall.",
                            MuscleGroup = "triceps",
                            Name = "Close-grip wall push-up"
                        },
                        new
                        {
                            Id = 9,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Stand facing a wall, place hands at chest height, and press with control.",
                            MuscleGroup = "chest",
                            Name = "Wall chest press"
                        },
                        new
                        {
                            Id = 10,
                            BeginnerAllowed = true,
                            Equipment = "resistance_band",
                            Instructions = "Use a secure band anchor and extend elbows without locking them.",
                            MuscleGroup = "triceps",
                            Name = "Band triceps press-down"
                        },
                        new
                        {
                            Id = 11,
                            BeginnerAllowed = true,
                            Equipment = "dumbbells",
                            Instructions = "Hinge slightly at the hips and raise light weights with control.",
                            MuscleGroup = "back",
                            Name = "Seated reverse fly"
                        },
                        new
                        {
                            Id = 12,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "From hands and knees, extend opposite arm and leg while keeping the trunk steady.",
                            MuscleGroup = "back",
                            Name = "Bird dog"
                        },
                        new
                        {
                            Id = 13,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Push hips back with a neutral spine, then stand tall.",
                            MuscleGroup = "legs",
                            Name = "Standing hip hinge"
                        },
                        new
                        {
                            Id = 14,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Lie on your back, press through your feet, and lift hips comfortably.",
                            MuscleGroup = "legs",
                            Name = "Glute bridge"
                        },
                        new
                        {
                            Id = 15,
                            BeginnerAllowed = true,
                            Equipment = "bodyweight",
                            Instructions = "Hold a stable support and lower only through a comfortable range.",
                            MuscleGroup = "legs",
                            Name = "Supported split squat"
                        });
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Days")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<string[]>("Equipment")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double>("HeightCm")
                        .HasColumnType("double precision");

                    b.Property<bool>("ReviewRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("SessionMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("UserId");

                    b.ToTable("Profiles", "fitness");
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessProgress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<bool>("Pain")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("PerformedOn")
                        .HasColumnType("date");

                    b.Property<int>("Rpe")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Day")
                        .IsUnique();

                    b.ToTable("Progress", "fitness", t =>
                        {
                            t.HasCheckConstraint("CK_Progress_Day", "\"Day\" BETWEEN 1 AND 7");

                            t.HasCheckConstraint("CK_Progress_Rpe", "\"Rpe\" BETWEEN 1 AND 10");
                        });
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PreviousWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("RevisionCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PreviousWorkflowId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("Workflows", "fitness");
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessApproval", b =>
                {
                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessEvent", b =>
                {
                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessProgress", b =>
                {
                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", b =>
                {
                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessWorkflow", null)
                        .WithMany()
                        .HasForeignKey("PreviousWorkflowId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VitroFit.API.Features.AdaptiveFitness.FitnessProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
