import { useState } from 'react';

const MEAL_ICONS = {
  breakfast: '🍳',
  lunch: '🥗',
  dinner: '🍽️',
  snack: '🍎',
};

const MEAL_FALLBACK_ICON = '🍽️';

/** Shared summary + meal breakdown, used by both the unsaved result preview and a saved plan's read-only view. */
function PlanDetails({ plan, hasMedicalConditions }) {
  const totalCalories = plan?.totalCalories ?? 0;
  const macros = plan?.macros ?? { protein: 0, carbs: 0, fat: 0 };
  const meals = plan?.meals ?? [];

  const mealCalories = (meal) =>
    (meal.items || []).reduce((sum, item) => sum + (item.calories || 0), 0);
  const icon = (type) => MEAL_ICONS[type?.toLowerCase()] || MEAL_FALLBACK_ICON;

  return (
    <>
      {/* Disclaimer — always shown, more prominent when medical conditions were selected */}
      <div className={`dp-disclaimer${hasMedicalConditions ? ' dp-disclaimer-strong' : ''}`}>
        This plan is generated by AI and is not medical advice.
        {hasMedicalConditions
          ? ' Given the medical condition(s) you selected, please consult a doctor or dietitian before following it.'
          : ' Consult a doctor or dietitian for guidance specific to your health.'}
      </div>

      {plan?.withinTolerance === false && (
        <div className="dp-warning-banner">
          This plan's totals may not exactly match your calorie/macro targets. You can
          regenerate it, or edit the meals below before confirming.
        </div>
      )}

      {/* Summary bar */}
      <div className="dp-summary">
        <div className="dp-summary-item">
          <span className="dp-summary-value">{totalCalories}</span>
          <span className="dp-summary-label">Daily Calories</span>
        </div>
        <div className="dp-summary-item">
          <span className="dp-summary-value">{macros.protein}g</span>
          <span className="dp-summary-label">Protein</span>
        </div>
        <div className="dp-summary-item">
          <span className="dp-summary-value">{macros.carbs}g</span>
          <span className="dp-summary-label">Carbs</span>
        </div>
        <div className="dp-summary-item">
          <span className="dp-summary-value">{macros.fat}g</span>
          <span className="dp-summary-label">Fat</span>
        </div>
      </div>

      {/* Meal cards */}
      <div className="dp-meals">
        {meals.map((meal, i) => (
          <div className="dp-meal" key={i}>
            <div className="dp-meal-head">
              <span className="dp-meal-icon">{icon(meal.type)}</span>
              <h3 className="dp-meal-title">{meal.label}</h3>
              <span className="dp-meal-calories">{mealCalories(meal)} kcal</span>
            </div>
            <ul className="dp-meal-items">
              {(meal.items || []).map((item, j) => (
                <li className="dp-meal-item" key={j}>
                  <div className="dp-meal-item-info">
                    <span className="dp-meal-item-name">{item.name}</span>
                    <span className="dp-meal-item-portion">{item.portion}</span>
                  </div>
                  <div className="dp-meal-item-meta">
                    <span className="dp-meal-item-cal">{item.calories} kcal</span>
                    <span className="dp-meal-item-macros">
                      P {item.macros?.protein ?? 0} · C {item.macros?.carbs ?? 0} · F {item.macros?.fat ?? 0}
                    </span>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </>
  );
}

function formatDate(iso) {
  return new Date(iso).toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
  });
}

/**
 * Diet plan results/display component.
 *
 * Handles states:
 *  - empty:   no plans ever saved yet (call to action to build the first one)
 *  - browse:  the logged-in user's saved plans, browsable with edit/delete/view
 *  - view:    a single saved plan's full read-only breakdown
 *  - loading: skeleton while the AI generates the plan
 *  - error:   the backend call failed (network, timeout, or the LLM couldn't produce a valid plan)
 *  - result:  a freshly generated (not yet saved) meal plan broken down by meal with macros & totals
 */
export default function DietPlanResult({
  state,
  plan,
  errorMessage,
  errorSteps = [],
  liveDetail = null,
  hasMedicalConditions,
  confirmStatus = 'idle',
  confirmErrorMessage,
  savedPlans = [],
  onGenerate,
  onEdit,
  onRegenerate,
  onConfirm,
  onCreateNew,
  onViewPlan,
  onEditPlan,
  onDeletePlan,
  onBack,
  onDelete,
  onRefine,
  refineStatus = 'idle',
  refineMessage = '',
  refineLiveDetail = null,
}) {
  if (state === 'empty') {
    return (
      <div className="dp-empty dp-fade-up">
        <div className="dp-empty-icon">🍽️</div>
        <h2 className="dp-empty-title">No Diet Plan Yet</h2>
        <p className="dp-empty-desc">
          Answer a few quick questions about your body, goals, and dietary
          preferences and we'll generate a personalised plan for you.
        </p>
        <button className="btn-primary" onClick={onGenerate}>
          Create a New Plan
        </button>
      </div>
    );
  }

  if (state === 'browse') {
    return (
      <div className="dp-browse dp-fade-up">
        <div className="dp-browse-head">
          <h2 className="dp-browse-title">Your Diet Plans</h2>
          <button className="btn-primary" onClick={onCreateNew}>
            + Create Another Plan
          </button>
        </div>
        <div className="dp-browse-list">
          {savedPlans.map((sp) => (
            <div
              className="dp-browse-card"
              key={sp.id}
              role="button"
              tabIndex={0}
              onClick={() => onViewPlan(sp)}
              onKeyDown={(e) => { if (e.key === 'Enter') onViewPlan(sp); }}
            >
              <div className="dp-browse-card-info">
                <span className="dp-browse-card-date">{formatDate(sp.createdAt)}</span>
                <span className="dp-browse-card-cal">{sp.totalCalories} kcal/day</span>
              </div>
              <div className="dp-browse-card-actions">
                <button
                  className="btn-secondary"
                  onClick={(e) => { e.stopPropagation(); onEditPlan(sp); }}
                >
                  Edit
                </button>
                <button
                  className="btn-secondary dp-btn-danger"
                  onClick={(e) => { e.stopPropagation(); onDeletePlan(sp.id); }}
                >
                  Delete
                </button>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  if (state === 'view') {
    return (
      <div className="dp-result dp-fade-up">
        <PlanDetails plan={plan} hasMedicalConditions={hasMedicalConditions} />
        <div className="dp-result-actions">
          <button className="btn-secondary" onClick={onBack}>
            Back to My Plans
          </button>
          <button className="btn-secondary" onClick={onEdit}>
            Edit
          </button>
          <button className="btn-secondary dp-btn-danger" onClick={onDelete}>
            Delete
          </button>
        </div>
      </div>
    );
  }

  if (state === 'error') {
    const attemptSteps = (errorSteps || []).filter((s) => s.agent === 'SafetyValidatorAgent');
    return (
      <div className="dp-empty dp-fade-up">
        <div className="dp-empty-icon">⚠️</div>
        <h2 className="dp-empty-title">Couldn't Generate Your Plan</h2>
        <p className="dp-empty-desc">
          {errorMessage || 'Something went wrong while generating your diet plan. Please try again.'}
        </p>
        {attemptSteps.length > 0 && (
          <div className="dp-disclaimer" style={{ textAlign: 'left', marginTop: '1rem' }}>
            <p style={{ margin: 0 }}>
              Our system tried {attemptSteps.length === 1 ? 'once' : `${attemptSteps.length} times`} to build a
              plan around your preferences:
            </p>
            <ul style={{ margin: '0.5rem 0 0', paddingLeft: '1.25rem' }}>
              {attemptSteps.map((step, i) => (
                <li key={i}>{describeAttemptStep(step)}</li>
              ))}
            </ul>
          </div>
        )}
        <div className="dp-result-actions">
          <button className="btn-secondary" onClick={onEdit}>
            Edit Preferences
          </button>
          <button className="btn-primary" onClick={onRegenerate}>
            Try Again
          </button>
        </div>
      </div>
    );
  }

  if (state === 'loading') {
    const liveSteps = liveDetail?.completedSteps || [];
    return (
      <div className="dp-loading dp-fade-up">
        <div className="dp-loading-top">
          <span className="dp-loader" />
          <h3 className="dp-loading-title">Generating your diet plan…</h3>
          {liveSteps.length === 0 && (
            <p className="dp-loading-desc">
              <AgentProgressText />
            </p>
          )}
        </div>
        {liveSteps.length > 0 && (
          <div className="dp-agent-cards">
            {liveSteps.map((step, i) => (
              <LiveStepCard key={i} step={step} detail={liveDetail} allSteps={liveSteps} />
            ))}
          </div>
        )}
        <div className="dp-skeleton-list">
          {[0, 1, 2, 3].map((m) => (
            <div className="dp-skeleton-meal" key={m}>
              <div className="dp-skeleton-label shimmer" />
              <div className="dp-skeleton-rows">
                {[0, 1, 2].map((r) => (
                  <div className="dp-skeleton-line shimmer" key={r} />
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  // state === 'result'
  return (
    <div className="dp-result dp-fade-up">
      <PlanDetails plan={plan} hasMedicalConditions={hasMedicalConditions} />

      <RefineBox
        onRefine={onRefine}
        refineStatus={refineStatus}
        refineMessage={refineMessage}
        refineLiveDetail={refineLiveDetail}
      />

      {/* Actions */}
      <div className="dp-result-actions">
        <button className="btn-secondary" onClick={onEdit}>
          Start Over
        </button>
        <button
          className="btn-primary"
          onClick={onConfirm}
          disabled={confirmStatus === 'saving' || confirmStatus === 'saved'}
        >
          {confirmStatus === 'saving' && 'Saving…'}
          {confirmStatus === 'saved' && 'Plan Saved ✓'}
          {(confirmStatus === 'idle' || confirmStatus === 'error') && 'Confirm Plan'}
        </button>
      </div>
      {confirmStatus === 'error' && (
        <p className="dp-field-err-text">
          {confirmErrorMessage || "Couldn't save your plan. Please try again."}
        </p>
      )}
      {confirmStatus === 'saved' && (
        <div className="dp-result-secondary-actions">
          <button className="btn-secondary" onClick={onBack}>
            Back to My Plans
          </button>
        </div>
      )}
    </div>
  );
}

/* Shown only for the very first instant, before the first real step has
   arrived from the backend - a one-line placeholder, not a simulated feed. */
function AgentProgressText() {
  return 'Starting up the Nutrition Analyst…';
}

const AGENT_META = {
  NutritionAnalystAgent: { icon: '🧮', label: 'Nutrition Analyst' },
  MealGeneratorAgent: { icon: '🧑‍🍳', label: 'Meal Generator' },
  SafetyValidatorAgent: { icon: '🛡️', label: 'Safety Validator' },
};

const RISK_FLAG_TEXT = {
  UNDER_18: "you're under 18",
  MEDICAL_CONDITIONS_PRESENT: 'you mentioned a medical condition',
  BELOW_SAFE_FLOOR: 'your calorie target would fall below a safe daily minimum (1,200 kcal)',
  STEEP_DEFICIT: "this plan cuts calories well below what your body burns at rest — a steep deficit",
};

function explainRisk(riskLevel, riskFlags) {
  const flagPhrases = (riskFlags || []).map((f) => RISK_FLAG_TEXT[f.code]).filter(Boolean);
  const intro =
    'Before any meals are drafted, I check a few safety signals: your age, any medical conditions you listed, ' +
    'and whether this target represents a steep calorie deficit compared to what your body actually burns.';

  if (riskLevel === 'low' || flagPhrases.length === 0) {
    return `${intro} None of those applied here, so this is a standard plan — it'll be generated and saved automatically, no extra sign-off needed.`;
  }
  const flagText = flagPhrases.join(' and ');
  if (riskLevel === 'high') {
    return (
      `${intro} Here, ${flagText}. Because of that, this plan is marked high risk: once it's generated, ` +
      `it will wait for a Trainer or Admin to personally review and approve it, rather than saving automatically.`
    );
  }
  return (
    `${intro} Here, ${flagText}. That's enough to flag for a closer look, but it doesn't block anything — ` +
    `this plan will still be generated and can be saved normally.`
  );
}

/**
 * Turns one real completedSteps entry (as polled live from
 * GET /workflows/{id}) into a detailed, plain-language explanation - not just
 * what happened, but what it means and why it matters. `detail` is the full
 * polled workflow response, used to pull in numbers (targets, risk, drafted
 * meals) a bare step entry doesn't carry by itself. Returns
 * {icon, label, variant, body} for LiveStepCard to render - this reflects
 * what the backend has actually finished, never a simulated guess.
 */
function describeLiveStep(step, detail, allSteps) {
  const meta = AGENT_META[step.agent] || { icon: '✓', label: step.agent };

  if (step.agent === 'NutritionAnalystAgent') {
    if (step.step === 1) {
      const t = detail?.targets;
      const body = t
        ? `Using your age, weight, height, and activity level, I worked out a daily target of ` +
          `${t.totalCalories} kcal. That's made up of ${t.macros?.protein}g of protein (what your body uses to ` +
          `repair and build muscle), ${t.macros?.carbs}g of carbohydrates (your main source of everyday energy), ` +
          `and ${t.macros?.fat}g of fat (needed for hormone production and absorbing certain vitamins). ` +
          `The Meal Generator will now try to fill in real meals that add up to these numbers — it's never allowed ` +
          `to invent its own target.`
        : 'Calculating your daily calorie and macro targets from your age, weight, height, and activity level…';
      return { ...meta, variant: 'default', body };
    }
    const flags = step.riskFlags ?? detail?.riskFlags;
    const risk = step.riskLevel ?? detail?.riskLevel;
    const body = risk
      ? explainRisk(risk, flags)
      : 'Checking whether anything about this plan (age, medical conditions, how big a calorie deficit it is) needs extra review…';
    const variant = risk === 'high' ? 'revise' : 'default';
    return { ...meta, variant, body };
  }

  if (step.agent === 'MealGeneratorAgent') {
    // detail.meals only ever holds the LATEST attempt's meals - only show
    // them for the most recent Meal Generator step in the list, or an
    // earlier retry entry would incorrectly display meals from a later try.
    const lastGenIndex = (allSteps || []).map((s) => s.agent).lastIndexOf('MealGeneratorAgent');
    const isLatestGenStep = !allSteps || allSteps.indexOf(step) === lastGenIndex;
    const meals = isLatestGenStep ? detail?.meals : null;
    const mealList = meals?.length ? meals.map((m) => m.label || m.type).join(', ') : null;
    const intro =
      "Meal Generator is the only agent allowed to call the AI model, and it can't touch the database or invent " +
      "its own calorie numbers — it only chooses real food items that add up toward the target Nutrition Analyst already set.";

    if (step.refine) {
      const body = mealList
        ? `${intro} For your requested change, it drafted an updated version of the plan (${mealList}) — Safety Validator will now re-check the whole thing before it's applied.`
        : `${intro} It's drafting an updated version of your plan based on what you asked for.`;
      return { ...meta, variant: 'default', body };
    }
    if (step.retry) {
      const body = mealList
        ? `${intro} The previous attempt didn't pass Safety Validator's checks, so this is try ${step.retry + 1}, using the specific feedback from that check: ${mealList}.`
        : `${intro} The previous attempt didn't pass Safety Validator's checks, so this is try ${step.retry + 1}, using that specific feedback to adjust.`;
      return { ...meta, variant: 'revise', body };
    }
    const body = mealList
      ? `${intro} For today, it drafted ${meals.length} meals: ${mealList}.`
      : `${intro} It's drafting a full day of meals now.`;
    return { ...meta, variant: 'default', body };
  }

  if (step.agent === 'SafetyValidatorAgent') {
    const violations = step.violations || [];
    const reason = violations.map((v) => v.message).filter(Boolean).slice(0, 2).join('; ');
    const otherReasons = violations
      .filter((v) => v.code !== 'CALORIE_OUT_OF_TOLERANCE')
      .map((v) => v.message)
      .filter(Boolean)
      .slice(0, 2)
      .join('; ');
    const direction = step.attemptCalories != null && step.targetCalories
      ? (step.attemptCalories < step.targetCalories ? 'under' : 'over')
      : null;
    const calorieNote = step.targetCalories
      ? `This attempt totals ${step.attemptCalories} kcal, which is ${step.diffPct}% ${direction} your ${step.targetCalories} kcal target`
      : null;
    const intro =
      "Safety Validator doesn't use AI at all — it runs fixed rules against the drafted meals: do the calories " +
      "land within about 10% of your daily target (VitroFit's tolerance band, so the numbers stay meaningful), " +
      "do the macros roughly add up, and does anything conflict with your dietary restrictions or medical conditions.";

    if (step.refine) {
      if (step.verdict === 'reject') {
        const body = reason
          ? `${intro} For your requested change, it found a problem: ${reason}. Because that's a dietary-safety rule and not just a numbers issue, the change is rejected outright and your plan stays exactly as it was.`
          : `${intro} For your requested change, it found the result would conflict with one of your restrictions, so the change was rejected and your plan stays exactly as it was.`;
        return { ...meta, variant: 'reject', body };
      }
      if (step.verdict === 'revise') {
        const body = reason
          ? `${intro} It flagged a minor issue (${reason}) but nothing that breaks a safety rule, so the change was still applied.`
          : `${intro} It flagged a minor issue but nothing that breaks a safety rule, so the change was still applied.`;
        return { ...meta, variant: 'revise', body };
      }
      return { ...meta, variant: 'pass', body: `${intro} Your requested change passed every check, so it's now part of your plan.` };
    }

    if (step.verdict === 'pass') {
      const body = calorieNote
        ? `${intro} ${calorieNote} — comfortably inside that 10% margin, and nothing conflicts with your restrictions, so this plan passes.`
        : `${intro} This plan passes every check.`;
      return { ...meta, variant: 'pass', body };
    }
    if (step.verdict === 'reject') {
      const body = reason
        ? `${intro} It found a problem that can't just be fixed by trying again: ${reason}. Since that's a safety rule, not a numbers nuance, VitroFit stops here instead of retrying.`
        : `${intro} It found a safety issue serious enough that trying again wouldn't help, so it stopped here.`;
      return { ...meta, variant: 'reject', body };
    }
    // revise
    const attemptLabel = step.attempt ? `attempt ${step.attempt}` : 'this attempt';
    const body = calorieNote
      ? `${intro} For ${attemptLabel}, ${calorieNote} — that's outside the 10% margin${otherReasons ? `, and: ${otherReasons}` : ''}. Rather than accepting an inaccurate plan, it's sending specific feedback back to Meal Generator to try again.`
      : `${intro} ${attemptLabel} wasn't quite on target, so it's asking Meal Generator to try again.`;
    return { ...meta, variant: 'revise', body };
  }

  return { icon: '✓', label: step.agent, variant: 'default', body: 'Finished this step.' };
}

/** One agent's progress explanation, styled as a themed card - larger, higher-contrast text than the surrounding page, color-coded by outcome. */
function LiveStepCard({ step, detail, allSteps }) {
  const info = describeLiveStep(step, detail, allSteps);
  return (
    <div className={`dp-agent-card dp-agent-card-${info.variant}`}>
      <div className="dp-agent-card-header">
        <span className="dp-agent-card-icon">{info.icon}</span>
        <span>{info.label}</span>
      </div>
      <p className="dp-agent-card-body">{info.body}</p>
    </div>
  );
}

/** A free-text "edit this plan" box, used on the result screen instead of restarting the whole form. */
function RefineBox({ onRefine, refineStatus, refineMessage, refineLiveDetail }) {
  const [instruction, setInstruction] = useState('');
  if (!onRefine) return null;

  const applying = refineStatus === 'applying';
  const refineSteps = (refineLiveDetail?.completedSteps || []).filter((s) => s.refine);

  const handleSubmit = (e) => {
    e.preventDefault();
    const trimmed = instruction.trim();
    if (!trimmed || applying) return;
    onRefine(trimmed);
    setInstruction('');
  };

  return (
    <div className="dp-refine-box">
      <p className="dp-refine-box-label">Want a small change?</p>
      <form onSubmit={handleSubmit} className="dp-refine-form">
        <input
          type="text"
          className="dp-refine-input"
          value={instruction}
          onChange={(e) => setInstruction(e.target.value)}
          placeholder="e.g. instead of rice, include something else at lunch"
          disabled={applying}
          maxLength={300}
        />
        <button type="submit" className="btn-secondary dp-refine-submit" disabled={applying || !instruction.trim()}>
          {applying && <span className="dp-refine-spinner" />}
          {applying ? 'Applying…' : 'Apply Change'}
        </button>
      </form>
      {applying && (
        <div className="dp-agent-cards dp-agent-cards-compact">
          {refineSteps.length === 0 ? (
            <p className="dp-refine-progress-placeholder">Looking at your plan…</p>
          ) : (
            refineSteps.map((s, i) => (
              <LiveStepCard key={i} step={s} detail={refineLiveDetail} allSteps={refineSteps} />
            ))
          )}
        </div>
      )}
      {(refineStatus === 'note' || refineStatus === 'error') && refineMessage && (
        <p className="dp-field-err-text dp-refine-message">{refineMessage}</p>
      )}
    </div>
  );
}

/** Plain-language, non-technical summary of one validator attempt, for customers rather than engineers. */
function describeAttemptStep(step) {
  const tryLabel = step.attempt ? `Try ${step.attempt}` : 'This try';
  const isSafetyIssue = (step.violations || []).some((v) => v.code === 'RESTRICTION_VIOLATION' || v.code === 'BELOW_SAFE_FLOOR');

  if (step.verdict === 'pass') {
    return `${tryLabel}: matched your calorie target and passed all checks.`;
  }
  if (isSafetyIssue) {
    // A dietary-safety issue (an ingredient conflicting with a restriction/
    // allergy, or a target below a safe calorie floor) is the real reason,
    // not the calorie miss - lead with that in plain terms.
    return `${tryLabel}: one of the suggested meals conflicted with a restriction, allergy, or safe calorie minimum you set.`;
  }
  if (step.targetCalories) {
    const direction = step.attemptCalories < step.targetCalories ? 'short of' : 'over';
    return `${tryLabel}: came out to about ${step.attemptCalories} calories — ${step.diffPct}% ${direction} your ${step.targetCalories}-calorie target.`;
  }
  return `${tryLabel}: didn't quite match your preferences.`;
}